### PR TITLE
add code style formatter for eclipse-java

### PR DESCRIPTION
**Pull request by sidharthamani**
@ibuildthecloud @hibooboo2 @alena1108

### CODE REVIEW

**Comment by ibuildthecloud** [comment]
There's a folder `tools/eclipse` do you think this should go there?

**Comment by sidharthamani** [comment]
yeah, that makes better sense.

**Comment by sidharthamani** [comment]
@ibuildthecloud I've pushed the formatter to tools/eclipse

**Comment by sidharthamani** [comment]
@ibuildthecloud   Now that @hibooboo2's checkstyle is in, Shall I close this PR?

**Pull request closed without merging**
