### PR TITLE
No need to wait for serviceMap create on instance.start

### PR DESCRIPTION
**Pull request by alena1108**
https://github.com/rancherio/rancher/issues/1311

### CODE REVIEW

**Comment by alena1108** [comment]
The "wait" was put originally as a part of initial healtcheck implementation (where health_state was defined on per exposeMap basis, so we had to ensure that the host map existed before instance registers for the healtcheck). Today healtcheck is defined on the instance itself, and we don't need anything extra for the instance to be registered.

**Comment by alena1108** [comment]
@cjellick @sonchang could you please review?

**Comment by sonchang** [comment]
LGTM

**Comment by cjellick** [comment]
LGTM

**Pull request merged**
