### PR TITLE
add documentation for machine fields

### PR DESCRIPTION
**Pull request by wlan0**
@ibuildthecloud @cjellick

### CODE REVIEW

**Comment by will-chan** [comment]
Shouldn't we be able to add some tests to validate this?

**Comment by wlan0** [comment]
This is machine-generated @will-chan. I'm not sure what kind of tests we could add.

**Comment by cjellick** [comment]
Maybe @will-chan is suggesting a test that reads the schema and verifies the description is set?
Since this documentation feature is already part of the framework, I don't think that's necessary.
LGTM.

**Comment by cjellick** [comment]
@wlan0 tests failed because of these changes. Please take a look.

**Pull request merged**
