### PR TITLE
it's possible to have some rare timing issues. also, deactivate servi…

### PR DESCRIPTION
**Pull request by sonchang**
…ce (esp. global)

at end of test

### CODE REVIEW

**Comment by sonchang** [comment]
@ibuildthecloud

**Comment by sonchang** [comment]
@alena1108 @ibuildthecloud 
Should fix the intermittent update_labels TF we get in drone.  The deactivation of global service wasn't necessary for this fix, but I figure it's good to not have those lying around since I'm not sure it plays nicely when we do the rest of the test teardown and I think could cause hangups downstream.

**Comment by alena1108** [comment]
LGTM

**Comment by cjellick** [comment]
LGTM

**Pull request merged**
