### PR TITLE
add tests for jwt authentication for host_api

### PR DESCRIPTION
**Pull request by pranavs18**
Need to run the tests locally once more. Sometimes the websocket connection fails, sometimes it's successful.

### CODE REVIEW

**Comment by ibuildthecloud** [comment]
Please put these tests in the validation test project

**Comment by pranavs18** [comment]
The build on Drone is going to fail as the python packages which get installed by default doesn't have the python websocket , websocket-client module. I had to install them separately on my local machine and activate my virtual environment again. @cloudnautique  You would need to probably add these two python packages - websocket, websocket-client.

**Comment by ibuildthecloud** [comment]
Why is this passing now?

**Comment by pranavs18** [comment]
Probably, because I moved it to the validation tests I assume ? Not sure ,if  drone runs the validation tests also ?

**Comment by ibuildthecloud** [comment]
There is a different project for validation twsts

**Comment by pranavs18** [comment]
Oh, just realized that. Moved this file to that project.

**Pull request closed without merging**
