### PR TITLE
Expose "update" action for loadBalancer object

### PR DESCRIPTION
**Pull request by alena1108**
@vincent99 

Here is the update action for LB. I've also reviewed test_lb.py (to make sure the update is tested there) and removed some unused vars

### CODE REVIEW

**Comment by alena1108** [comment]
@vincent99 @cjellick Vince, Craig, can you pls review this PR? It just exposes the update action for the load balancer. Functionality was already there, as well as the test

**Comment by cjellick** [comment]
LGTM

**Comment by sonchang** [comment]
@alena1108 was the change to the integration test just code cleanup?  if so, then LGTM

**Comment by cjellick** [comment]
confirmed it was just cleanup

**Comment by sonchang** [comment]
LGTM

**Pull request merged**
