### PR TITLE
add new generic drivers

### PR DESCRIPTION
**Pull request by wlan0**
@ibuildthecloud

### CODE REVIEW

**Comment by wlan0** [comment]
unrelated test failed.

**Comment by wlan0** [comment]
@cjellick Rebased and Repushed. Once again unrelated test failure.

**Comment by cjellick** [comment]
Where'd my LGTM go?
Anyway, LGTM. Ping @alena1108 or @sonchang to make it official.

**Comment by will-chan** [comment]
LGTM

**Pull request merged**
