### PR TITLE
WIP : Bugfix

### PR DESCRIPTION
**Pull request by sidharthamani**

### CODE REVIEW

**Comment by ibuildthecloud** [comment]
@sidharthamani split this into two PRs.  the nullable change should go first.  I'm sure the admin one will have issues, so lets at least get the nullable on master now.

**Comment by vincent99** [comment]
nullable + clientSecret should go first

**Comment by ibuildthecloud** [comment]
@sidharthamani this is no good.  we can't just change the tests, if the test fails we need to know why and see if something on the server side needs to change.  I'll start looking at these

**Comment by sidharthamani** [comment]
@ibuildthecloud I understand. This PR is a WIP.

**Pull request closed without merging**
