### PR TITLE
Start over from green master

### PR DESCRIPTION
**Pull request by cjellick**

### CODE REVIEW

**Comment by cjellick** [comment]
Run:
http://drone.rancher.io/github.com/rancherio/cattle/pytest-xdist3/b3defecbffe40baeb60ce9bca595a747f73082b3

Failures
test_link_create
test_remove_inactive_service

**Comment by cjellick** [comment]
Failures
test_link_remove_restore

http://drone.rancher.io/github.com/rancherio/cattle/pytest-xdist3/81ed116136a4018be6d02680f9f529cb7a42a028

This was the skip known failures run. So, the test_link_create failure basically shifted

**Comment by cjellick** [comment]
sleep theory got passed all the tests, but the H2 tests blew up because of a syntax problem with how we start it up.

**Comment by cjellick** [comment]
failure
test_lb_instance

http://drone.rancher.io/github.com/rancherio/cattle/pytest-xdist3/cff5a28a7ac14beac8ae47c0f01161f2ab7fbec6

This was after the H2-test's syntax fix.

**Comment by cjellick** [comment]
failures:
test_docker_volumes
test_delete_host_from_lb_when_instance_stopped

http://drone.rancher.io/github.com/rancherio/cattle/pytest-xdist3/67d56ef86d1d111bc928962afb9c2c90d23d1b35

No changes in this run, just another run

**Comment by ibuildthecloud** [comment]
Last failing build looks like a legit error in the dns generation.  I ping @alena1108 about it already basically this error

```
evaluated to null or missing:
==> dnsEntry.sourceIpAddress.address  [in template "jar:injar:jar___file___/var/cache/drone/src/github.com/rancherio/cattle/code/packaging/app/target/cattle-app-0.5.0-SNAPSHOT.war__/WEB-INF/lib/cattle-resources-0.5.0-SNAPSHOT.jar!/config-content/hosts/content-home/etc/cattle/dns/answers.json.ftl" at line 10, column 8]

Tip: If the failing expression is known to be legally null/missing, either specify a default value with myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthessis: (myOptionVar.foo)!myDefault, (myOptionVar.foo)??

The failing instruction:
==> ${dnsEntry.sourceIpAddress.address}  [in template "jar:injar:jar___file___/var/cache/drone/src/github.com/rancherio/cattle/code/packaging/app/target/cattle-app-0.5.0-SNAPSHOT.war__/WEB-INF/lib/cattle-resources-0.5.0-SNAPSHOT.jar!/config-content/hosts/content-home/etc/cattle/dns/answers.json.ftl" at line 10, column 6]
```

There's tons trying to delete while deactivating errors.  I'm wondering if it is from delete_sim_instances cattletest/core/common_fixtures.py:453.  That method was supposed to be a catch to delete possibly orphaned accounts.  If it instead runs before `new_context` cleanup then it would do bad things, especially since it doesn't wait on deactivate.

**Comment by cjellick** [comment]
@ibuildthecloud I've skipped a few tests too that fail very consistently. I'm fairly certain that these are legit bugs that appear with load. They are:
test_container_affinity
test_remove_inactive_service

Will dig in more later, just wanted to make note.

**Comment by cjellick** [comment]
The test_host_only.py seem to fail somewhat consistently too.

**Comment by ibuildthecloud** [comment]
Aren't you at all curious what happens when you do `$(nproc)`?

**Comment by alena1108** [comment]
Fix for _validate_compose_instance_removed failure will come as a part of https://github.com/rancherio/cattle/pull/457 PR

**Pull request closed without merging**
