### PR TITLE
add hostlabel support

### PR DESCRIPTION
**Pull request by wlan0**
@cjellick @will-chan

### CODE REVIEW

**Comment by will-chan** [comment]
You need to add integration tests to test this new field.

**Comment by cjellick** [comment]
Hrm. A flake8 error snuck into master. Not your problem I guess.

**Comment by cjellick** [comment]
Agree with Will regarding the test. Other than that, LGTM.
It would be great if we could get this field added to one of the validation tests as well, but I won't hold up merging this waiting on that.

**Comment by will-chan** [comment]
LGTM

**Comment by ibuildthecloud** [comment]
flake8 error is my fault.  LGTM.  @cjellick I'll let you merge as I don't know what's going on with this feature.

**Comment by cjellick** [comment]
Ping @wlan0, in case you were waiting on this to be merged before submitting a go-rancher PR.

**Pull request merged**
