### PR TITLE
LB: don't set healthcheck "uri" and policy "domain" if their values are empty

### PR DESCRIPTION
**Pull request by alena1108**
https://github.com/rancherio/rancher/issues/469

### CODE REVIEW

**Comment by alena1108** [comment]
Fixes https://github.com/rancherio/rancher/issues/472

**Comment by alena1108** [comment]
@cjellick @sonchang could you please help reviewing?

**Comment by sonchang** [comment]
LGTM

**Comment by vincent99** [comment]
Were we still going to rename `uri`?

**Comment by alena1108** [comment]
@vincent99 I will rename it as a part of separate PR

**Comment by cjellick** [comment]
LGTM

**Pull request merged**
